language: cpp
sudo: false

env:
  global:
    - BUILD_TYPE=Debug

dist: trusty

matrix:
  include:
    # -- core library tests
    - os: linux
      addons:
        apt:
          sources: &ubuntu-sources [kubuntu-backports, ubuntu-toolchain-r-test, george-edison55-precise-backports, deadsnakes]
          packages:  &ubuntu-packages [cmake, g++-5, ninja-build]

    # -- python 3.5
    - os: linux
      env: PYTHON=3.5 CMAKE_EXTRA_ARGS="-Dsparsesolvers_WITH_PYTHON=ON"
      addons:
        apt:
          sources: *ubuntu-sources
          packages: [*ubuntu-packages, python3.5-dev]
      install:
        - pyenv versions
        - pyenv global $PYTHON
        - pip install --user --upgrade pip
        - pip install --user numpy wheel
        
cache:
  directories:
  - $HOME/.ccache
  - $HOME/download

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export COMPILER=g++-5   ; fi
  - mkdir build && cd build
  - cmake -GNinja ${CMAKE_EXTRA_ARGS} .. -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=$BUILD_TYPE
  - cmake --build .

script:
  - ctest . -VV -C $BUILD_TYPE

notifications:
  email: false